---
# Playbook to add additional users
# Call with
#  `ansible-playbook -i 127.0.0.1, additional_ansible_users.yml`
#  `ansible-playbook -i localhost, additional_ansible_users.yml`
#  `ansible-playbook -i 10.2.3.4, additional_ansible_users.yml`
#  `ansible-playbook -i host.suffix.com, additional_ansible_users.yml`

- hosts: localhost
  connection: local
  become: yes
  gather_facts: no
  tasks:
    - name: Ensure ansible group exists
      group:
        name: ansible
        state: present
    - name: Add users to the ansible group
      user:
        name: "{{ item.id }}"
        comment: "{{ item.name }}"
        group: ansible
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
        state: present
      loop:
        - { id: 'rita', name: 'Rita Hayworth' }
        - { id: 'sue',  name: 'Sue Perkins' }
        - { id: 'bob',  name: 'Bob Odenkirk' }
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
...
