---
# Master playbook to test custom role to install Ansible
- hosts: all
  become: yes
  roles:
      - role: azure_ansible
  vars:
    files:
      - ansible.cfg
      - example_playbook.yml
      - inventory.azure_rm.yml
    required_roles:
      - src: https://github.com/richeney/ansible-role-common
        name: common
      - src: https://github.com/richeney/ansible-role-azure-cli
        name: azure_cli
      - src: geerlingguy.pip
        name: pip
      - src: geerlingguy.docker
        name: docker
      - src: darkwizard242.terraform
        name: terraform
      - src: darkwizard242.packer
        name: packer
...
